# Generated by Django 4.0.3 on 2022-04-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='cancellation_description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
