# Generated by Django 4.0.3 on 2022-04-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0002_ordermodel_cancellation_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_gallery_image', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('second_gallery_image', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('third_gallery_image', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('fourth_gallery_image', models.FileField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image1',
            field=models.FileField(default=None, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product_images/'),
        ),
    ]
