# Generated by Django 4.0.3 on 2022-04-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0003_gallery_productmodel_image1_productmodel_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
