# Generated by Django 4.0.3 on 2022-04-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0004_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image2',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image3',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image4',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
    ]
