# Generated by Django 4.0.3 on 2022-04-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0005_alter_productmodel_image2_alter_productmodel_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image4',
        ),
    ]
