# Generated by Django 4.0.3 on 2022-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0006_remove_productmodel_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image1',
            field=models.FileField(default=None, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image4',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
    ]
