# Generated by Django 4.0.3 on 2022-04-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0007_productmodel_image1_productmodel_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='first_gallery_image',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/gallery/'),
        ),
    ]
