# Generated by Django 4.0.3 on 2022-04-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0009_alter_gallery_first_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cancellation_description',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
