# Generated by Django 4.0 on 2022-06-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0011_alter_gallery_first_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='feature_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image1',
            field=models.FileField(blank=True, default=None, upload_to='product_images/'),
        ),
    ]
