# Generated by Django 4.0 on 2022-06-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0012_productmodel_feature_flag_alter_productmodel_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
