# Generated by Django 4.0 on 2022-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0013_remove_productmodel_category_delete_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
