# Generated by Django 4.0.1 on 2022-03-05 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Category ID')),
                ('cat_name', models.CharField(default=None, max_length=100, verbose_name='Category Name')),
                ('cat_desc', models.JSONField(verbose_name='Category Description (in JSON)')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('c_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('c_img', models.FileField(blank=True, default=None, upload_to='media/customer_images', verbose_name='Customer Image')),
                ('c_name', models.CharField(default=None, max_length=100, verbose_name='Customer Name')),
                ('c_email', models.EmailField(default=None, max_length=100, verbose_name='Customer Email')),
                ('c_password', models.CharField(default=None, max_length=100, verbose_name='Customer Password')),
                ('c_phone', models.CharField(default=None, max_length=100, verbose_name='Customer Phone')),
                ('c_address', models.CharField(default=None, max_length=100, verbose_name='Customer Address')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('prod_name', models.CharField(default=None, max_length=100, verbose_name='Product Name')),
                ('prod_img', models.FileField(default=None, upload_to='media/product_images', verbose_name='Product Image')),
                ('prod_desc', models.TextField(verbose_name='Product Description')),
                ('prod_price', models.FloatField(default=None, verbose_name='Product Price')),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwuDB.categories', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('ord_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('ord_status', models.CharField(default='False', max_length=100, verbose_name='Cancellation Status')),
                ('ord_delivery_status', models.CharField(default='7 days', max_length=100, verbose_name='Delivery Status')),
                ('ord_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('ord_price', models.FloatField(blank=True, default=None, verbose_name='Order Price')),
                ('ord_gst', models.CharField(default='null', max_length=100, verbose_name='GST No.')),
                ('ord_qty', models.IntegerField(default=None, verbose_name='Quantity')),
                ('ord_refund_type', models.CharField(default='False', max_length=100, verbose_name='Order Refund Status')),
                ('ord_refund_img', models.FileField(blank=True, default=None, upload_to='media/order_refund_images', verbose_name='Passbook Image')),
                ('ord_feedback', models.TextField(default=None, max_length=100, verbose_name='Feedback')),
                ('ord_bill', models.FileField(default=None, upload_to='media/order_bills', verbose_name='Generated Bill')),
                ('ord_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwuDB.products', verbose_name='Product Name')),
                ('ord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwuDB.usermodel', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
