# Generated by Django 4.0.1 on 2022-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ord_image',
            field=models.FileField(blank=True, null=True, upload_to='order/customised_images/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_refund_cheque',
            field=models.FileField(blank=True, upload_to='order/OrderRefund/'),
        ),
    ]
