# Generated by Django 4.0.1 on 2022-03-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='ord_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='ord_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='ord_price',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='quantity',
            new_name='ord_quantity',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='ord_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='ord_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
