# Generated by Django 4.0.1 on 2022-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0002_orders_ord_image_alter_orders_user_refund_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
