# Generated by Django 4.0.1 on 2022-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0002_orders_ord_image_alter_orders_user_refund_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='product/product_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='product/product_images/'),
        ),
    ]
