# Generated by Django 4.0.1 on 2022-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0003_products_image1_products_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
