# Generated by Django 4.0.1 on 2022-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0004_orders_cancellation_date_orders_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
