# Generated by Django 4.0.1 on 2022-03-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0006_remove_orders_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
