# Generated by Django 4.0.1 on 2022-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0008_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(default='None', upload_to='product/product_images/'),
        ),
    ]
