# Generated by Django 4.0.1 on 2022-03-17 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0009_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Coupon ID')),
                ('name', models.CharField(max_length=40, verbose_name='Coupon Name')),
                ('discount', models.FloatField(default=0, max_length=40, verbose_name='Discount Percent')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
