# Generated by Django 4.0.1 on 2022-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwuDB', '0010_coupon_alter_categories_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Coupon Name'),
        ),
    ]
