# Generated by Django 4.0.1 on 2022-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_user_id_alter_userdata_user_ptr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_merchant',
            field=models.BooleanField(default=False, help_text='Check if you are a merchant', verbose_name='Merchant'),
        ),
    ]
