# Generated by Django 4.0.1 on 2022-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cartdatamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdatamodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartdatamodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartdatamodel',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
