# Generated by Django 4.0.1 on 2022-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cartdatamodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdatamodel',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
